In [36]:
from pymongo import MongoClient
import pandas as pd

In [37]:
client = MongoClient("mongodb://localhost:27017/")
collection = client["lendingclub_db"]["loans_raw"]

In [38]:
df = pd.DataFrame(list(collection.find()))

# Drop the MongoDB internal _id column
df = df.drop(columns=["_id"])
df.head()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,...,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 75 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   466285 non-null  int64
 1   id                           466285 non-null  int64
 2   member_id                    466285 non-null  int64
 3   loan_amnt                    466285 non-null  int64
 4   funded_amnt                  466285 non-null  int64
 5   funded_amnt_inv              466285 non-null  float64
 6   term                         466285 non-null  object
 7   int_rate                     466285 non-null  float64
 8   installment                  466285 non-null  float64
 9   grade                        466285 non-null  object
 10  sub_grade                    466285 non-null  object
 11  emp_title                    438697 non-null  object
 12  emp_length                   445277 non-null  object
 13  home_ownership               466285 non-null  object
 14  annual_inc                   466281 non-null  float64
 15  verification_status          466285 non-null  object
 16  issue_d                      466285 non-null  object
 17  loan_status                  466285 non-null  object
 18  pymnt_plan                   466285 non-null  object
 19  url                          466285 non-null  object
 20  desc                         125981 non-null  object
 21  purpose                      466285 non-null  object
 22  title                        466264 non-null  object
 23  zip_code                     466285 non-null  object
 24  addr_state                   466285 non-null  object
 25  dti                          466285 non-null  float64
 26  delinq_2yrs                  466256 non-null  float64
 27  earliest_cr_line             466256 non-null  object
 28  inq_last_6mths               466256 non-null  float64
 29  mths_since_last_delinq       215934 non-null  float64
 30  mths_since_last_record       62638 non-null   float64
 31  open_acc                     466256 non-null  float64
 32  pub_rec                      466256 non-null  float64
 33  revol_bal                    466285 non-null  int64
 34  revol_util                   465945 non-null  float64
 35  total_acc                    466256 non-null  float64
 36  initial_list_status          466285 non-null  object
 37  out_prncp                    466285 non-null  float64
 38  out_prncp_inv                466285 non-null  float64
 39  total_pymnt                  466285 non-null  float64
 40  total_pymnt_inv              466285 non-null  float64
 41  total_rec_prncp              466285 non-null  float64
 42  total_rec_int                466285 non-null  float64
 43  total_rec_late_fee           466285 non-null  float64
 44  recoveries                   466285 non-null  float64
 45  collection_recovery_fee      466285 non-null  float64
 46  last_pymnt_d                 465909 non-null  object
 47  last_pymnt_amnt              466285 non-null  float64
 48  next_pymnt_d                 239071 non-null  object
 49  last_credit_pull_d           466243 non-null  object
 50  collections_12_mths_ex_med   466140 non-null  float64
 51  mths_since_last_major_derog  98974 non-null   float64
 52  policy_code                  466285 non-null  int64
 53  application_type             466285 non-null  object
 54  annual_inc_joint             0 non-null       float64
 55  dti_joint                    0 non-null       float64
 56  verification_status_joint    0 non-null       float64
 57  acc_now_delinq               466256 non-null  float64
 58  tot_coll_amt                 396009 non-null  float64
 59  tot_cur_bal                  396009 non-null  float64
 60  open_acc_6m                  0 non-null       float64
 61  open_il_6m                   0 non-null       float64
 62  open_il_12m                  0 non-null       float64
 63  open_il_24m                  0 non-null       float64
 64  mths_since_rcnt_il           0 non-null       float64
 65  total_bal_il                 0 non-null       float64
 66  il_util                      0 non-null       float64
 67  open_rv_12m                  0 non-null       float64
 68  open_rv_24m                  0 non-null       float64
 69  max_bal_bc                   0 non-null       float64
 70  all_util                     0 non-null       float64
 71  total_rev_hi_lim             396009 non-null  float64
 72  inq_fi                       0 non-null       float64
 73  total_cu_tl                  0 non-null       float64
 74  inq_last_12m                 0 non-null       float64
dtypes: float64(46), int64(7), object(22)
memory usage: 266.8+ MB

In [40]:
df.dropna(how='all', axis=1, inplace=True)
df.drop(columns=['Unnamed: 0','id','member_id','url','desc'], inplace=True)

for col in df.columns:
    if df[col].isnull().any():
        df.dropna(subset=[col], inplace=True)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9367 entries, 42597 to 466274
Data columns (total 53 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   loan_amnt                    9367 non-null   int64
 1   funded_amnt                  9367 non-null   int64
 2   funded_amnt_inv              9367 non-null   float64
 3   term                         9367 non-null   object
 4   int_rate                     9367 non-null   float64
 5   installment                  9367 non-null   float64
 6   grade                        9367 non-null   object
 7   sub_grade                    9367 non-null   object
 8   emp_title                    9367 non-null   object
 9   emp_length                   9367 non-null   object
 10  home_ownership               9367 non-null   object
 11  annual_inc                   9367 non-null   float64
 12  verification_status          9367 non-null   object
 13  issue_d                      9367 non-null   object
 14  loan_status                  9367 non-null   object
 15  pymnt_plan                   9367 non-null   object
 16  purpose                      9367 non-null   object
 17  title                        9367 non-null   object
 18  zip_code                     9367 non-null   object
 19  addr_state                   9367 non-null   object
 20  dti                          9367 non-null   float64
 21  delinq_2yrs                  9367 non-null   float64
 22  earliest_cr_line             9367 non-null   object
 23  inq_last_6mths               9367 non-null   float64
 24  mths_since_last_delinq       9367 non-null   float64
 25  mths_since_last_record       9367 non-null   float64
 26  open_acc                     9367 non-null   float64
 27  pub_rec                      9367 non-null   float64
 28  revol_bal                    9367 non-null   int64
 29  revol_util                   9367 non-null   float64
 30  total_acc                    9367 non-null   float64
 31  initial_list_status          9367 non-null   object
 32  out_prncp                    9367 non-null   float64
 33  out_prncp_inv                9367 non-null   float64
 34  total_pymnt                  9367 non-null   float64
 35  total_pymnt_inv              9367 non-null   float64
 36  total_rec_prncp              9367 non-null   float64
 37  total_rec_int                9367 non-null   float64
 38  total_rec_late_fee           9367 non-null   float64
 39  recoveries                   9367 non-null   float64
 40  collection_recovery_fee      9367 non-null   float64
 41  last_pymnt_d                 9367 non-null   object
 42  last_pymnt_amnt              9367 non-null   float64
 43  next_pymnt_d                 9367 non-null   object
 44  last_credit_pull_d           9367 non-null   object
 45  collections_12_mths_ex_med   9367 non-null   float64
 46  mths_since_last_major_derog  9367 non-null   float64
 47  policy_code                  9367 non-null   int64
 48  application_type             9367 non-null   object
 49  acc_now_delinq               9367 non-null   float64
 50  tot_coll_amt                 9367 non-null   float64
 51  tot_cur_bal                  9367 non-null   float64
 52  total_rev_hi_lim             9367 non-null   float64
dtypes: float64(29), int64(4), object(20)
memory usage: 3.9+ MB

In [42]:
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9367 entries, 42597 to 466274
Data columns (total 53 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   loan_amnt                    9367 non-null   int64
 1   funded_amnt                  9367 non-null   int64
 2   funded_amnt_inv              9367 non-null   float64
 3   term                         9367 non-null   object
 4   int_rate                     9367 non-null   float64
 5   installment                  9367 non-null   float64
 6   grade                        9367 non-null   object
 7   sub_grade                    9367 non-null   object
 8   emp_title                    9367 non-null   object
 9   emp_length                   9367 non-null   object
 10  home_ownership               9367 non-null   object
 11  annual_inc                   9367 non-null   float64
 12  verification_status          9367 non-null   object
 13  issue_d                      9367 non-null   object
 14  loan_status                  9367 non-null   object
 15  pymnt_plan                   9367 non-null   object
 16  purpose                      9367 non-null   object
 17  title                        9367 non-null   object
 18  zip_code                     9367 non-null   object
 19  addr_state                   9367 non-null   object
 20  dti                          9367 non-null   float64
 21  delinq_2yrs                  9367 non-null   float64
 22  earliest_cr_line             9367 non-null   object
 23  inq_last_6mths               9367 non-null   float64
 24  mths_since_last_delinq       9367 non-null   float64
 25  mths_since_last_record       9367 non-null   float64
 26  open_acc                     9367 non-null   float64
 27  pub_rec                      9367 non-null   float64
 28  revol_bal                    9367 non-null   int64
 29  revol_util                   9367 non-null   float64
 30  total_acc                    9367 non-null   float64
 31  initial_list_status          9367 non-null   object
 32  out_prncp                    9367 non-null   float64
 33  out_prncp_inv                9367 non-null   float64
 34  total_pymnt                  9367 non-null   float64
 35  total_pymnt_inv              9367 non-null   float64
 36  total_rec_prncp              9367 non-null   float64
 37  total_rec_int                9367 non-null   float64
 38  total_rec_late_fee           9367 non-null   float64
 39  recoveries                   9367 non-null   float64
 40  collection_recovery_fee      9367 non-null   float64
 41  last_pymnt_d                 9367 non-null   object
 42  last_pymnt_amnt              9367 non-null   float64
 43  next_pymnt_d                 9367 non-null   object
 44  last_credit_pull_d           9367 non-null   object
 45  collections_12_mths_ex_med   9367 non-null   float64
 46  mths_since_last_major_derog  9367 non-null   float64
 47  policy_code                  9367 non-null   int64
 48  application_type             9367 non-null   object
 49  acc_now_delinq               9367 non-null   float64
 50  tot_coll_amt                 9367 non-null   float64
 51  tot_cur_bal                  9367 non-null   float64
 52  total_rev_hi_lim             9367 non-null   float64
dtypes: float64(29), int64(4), object(20)
memory usage: 3.9+ MB

In [43]:
date_list=['issue_d','earliest_cr_line','last_pymnt_d','next_pymnt_d','last_credit_pull_d']
for date in date_list:
    df.drop(columns=[date], inplace=True)

In [44]:
df['term'] = (df['term'].str.replace(' months', '').astype(int))
df['emp_length'] = df['emp_length'].fillna('0').str.replace(' years', '').str.replace(' year', '').str.replace('< 1', '0').str.replace('10+', '10').astype(int)
df[['term','emp_length']].head()

       term  emp_length
42597    36           1
42630    36           2
42664    36           8
42667    60           8
42677    36          10

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9367 entries, 42597 to 466274
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   loan_amnt                    9367 non-null   int64
 1   funded_amnt                  9367 non-null   int64
 2   funded_amnt_inv              9367 non-null   float64
 3   term                         9367 non-null   int64
 4   int_rate                     9367 non-null   float64
 5   installment                  9367 non-null   float64
 6   grade                        9367 non-null   object
 7   sub_grade                    9367 non-null   object
 8   emp_title                    9367 non-null   object
 9   emp_length                   9367 non-null   int64
 10  home_ownership               9367 non-null   object
 11  annual_inc                   9367 non-null   float64
 12  verification_status          9367 non-null   object
 13  loan_status                  9367 non-null   object
 14  pymnt_plan                   9367 non-null   object
 15  purpose                      9367 non-null   object
 16  title                        9367 non-null   object
 17  zip_code                     9367 non-null   object
 18  addr_state                   9367 non-null   object
 19  dti                          9367 non-null   float64
 20  delinq_2yrs                  9367 non-null   float64
 21  inq_last_6mths               9367 non-null   float64
 22  mths_since_last_delinq       9367 non-null   float64
 23  mths_since_last_record       9367 non-null   float64
 24  open_acc                     9367 non-null   float64
 25  pub_rec                      9367 non-null   float64
 26  revol_bal                    9367 non-null   int64
 27  revol_util                   9367 non-null   float64
 28  total_acc                    9367 non-null   float64
 29  initial_list_status          9367 non-null   object
 30  out_prncp                    9367 non-null   float64
 31  out_prncp_inv                9367 non-null   float64
 32  total_pymnt                  9367 non-null   float64
 33  total_pymnt_inv              9367 non-null   float64
 34  total_rec_prncp              9367 non-null   float64
 35  total_rec_int                9367 non-null   float64
 36  total_rec_late_fee           9367 non-null   float64
 37  recoveries                   9367 non-null   float64
 38  collection_recovery_fee      9367 non-null   float64
 39  last_pymnt_amnt              9367 non-null   float64
 40  collections_12_mths_ex_med   9367 non-null   float64
 41  mths_since_last_major_derog  9367 non-null   float64
 42  policy_code                  9367 non-null   int64
 43  application_type             9367 non-null   object
 44  acc_now_delinq               9367 non-null   float64
 45  tot_coll_amt                 9367 non-null   float64
 46  tot_cur_bal                  9367 non-null   float64
 47  total_rev_hi_lim             9367 non-null   float64
dtypes: float64(29), int64(6), object(13)
memory usage: 3.5+ MB

In [46]:
df.dropna(how='all', axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9367 entries, 42597 to 466274
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   loan_amnt                    9367 non-null   int64
 1   funded_amnt                  9367 non-null   int64
 2   funded_amnt_inv              9367 non-null   float64
 3   term                         9367 non-null   int64
 4   int_rate                     9367 non-null   float64
 5   installment                  9367 non-null   float64
 6   grade                        9367 non-null   object
 7   sub_grade                    9367 non-null   object
 8   emp_title                    9367 non-null   object
 9   emp_length                   9367 non-null   int64
 10  home_ownership               9367 non-null   object
 11  annual_inc                   9367 non-null   float64
 12  verification_status          9367 non-null   object
 13  loan_status                  9367 non-null   object
 14  pymnt_plan                   9367 non-null   object
 15  purpose                      9367 non-null   object
 16  title                        9367 non-null   object
 17  zip_code                     9367 non-null   object
 18  addr_state                   9367 non-null   object
 19  dti                          9367 non-null   float64
 20  delinq_2yrs                  9367 non-null   float64
 21  inq_last_6mths               9367 non-null   float64
 22  mths_since_last_delinq       9367 non-null   float64
 23  mths_since_last_record       9367 non-null   float64
 24  open_acc                     9367 non-null   float64
 25  pub_rec                      9367 non-null   float64
 26  revol_bal                    9367 non-null   int64
 27  revol_util                   9367 non-null   float64
 28  total_acc                    9367 non-null   float64
 29  initial_list_status          9367 non-null   object
 30  out_prncp                    9367 non-null   float64
 31  out_prncp_inv                9367 non-null   float64
 32  total_pymnt                  9367 non-null   float64
 33  total_pymnt_inv              9367 non-null   float64
 34  total_rec_prncp              9367 non-null   float64
 35  total_rec_int                9367 non-null   float64
 36  total_rec_late_fee           9367 non-null   float64
 37  recoveries                   9367 non-null   float64
 38  collection_recovery_fee      9367 non-null   float64
 39  last_pymnt_amnt              9367 non-null   float64
 40  collections_12_mths_ex_med   9367 non-null   float64
 41  mths_since_last_major_derog  9367 non-null   float64
 42  policy_code                  9367 non-null   int64
 43  application_type             9367 non-null   object
 44  acc_now_delinq               9367 non-null   float64
 45  tot_coll_amt                 9367 non-null   float64
 46  tot_cur_bal                  9367 non-null   float64
 47  total_rev_hi_lim             9367 non-null   float64
dtypes: float64(29), int64(6), object(13)
memory usage: 3.5+ MB

In [47]:
collection_clean = client["lendingclub_db"]["loans_clean"]
collection_clean.insert_many(df.to_dict('records'))