# Task 1: Data Loading & Exploration
In this part, we will be mainly focused on loading the data while exploring it with graph before we get into the next stage, which is cleaning.

## Library Import
Below are the library we imported for loading and exploring the loan dataset

In [190]:
from pymongo import MongoClient
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [191]:
client = MongoClient("mongodb://localhost:27017/")
collection = client["lendingclub_db"]["loans_raw"]

In [192]:
df = pd.DataFrame(list(collection.find()))

# Drop the MongoDB internal _id column
df = df.drop(columns=["_id"])
df.head()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,...,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [193]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 75 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   466285 non-null  int64
 1   id                           466285 non-null  int64
 2   member_id                    466285 non-null  int64
 3   loan_amnt                    466285 non-null  int64
 4   funded_amnt                  466285 non-null  int64
 5   funded_amnt_inv              466285 non-null  float64
 6   term                         466285 non-null  object
 7   int_rate                     466285 non-null  float64
 8   installment                  466285 non-null  float64
 9   grade                        466285 non-null  object
 10  sub_grade                    466285 non-null  object
 11  emp_title                    438697 non-null  object
 12  emp_length                   445277 non-null  object
 13  home_ownership               466285 non-null  object
 14  annual_inc                   466281 non-null  float64
 15  verification_status          466285 non-null  object
 16  issue_d                      466285 non-null  object
 17  loan_status                  466285 non-null  object
 18  pymnt_plan                   466285 non-null  object
 19  url                          466285 non-null  object
 20  desc                         125981 non-null  object
 21  purpose                      466285 non-null  object
 22  title                        466264 non-null  object
 23  zip_code                     466285 non-null  object
 24  addr_state                   466285 non-null  object
 25  dti                          466285 non-null  float64
 26  delinq_2yrs                  466256 non-null  float64
 27  earliest_cr_line             466256 non-null  object
 28  inq_last_6mths               466256 non-null  float64
 29  mths_since_last_delinq       215934 non-null  float64
 30  mths_since_last_record       62638 non-null   float64
 31  open_acc                     466256 non-null  float64
 32  pub_rec                      466256 non-null  float64
 33  revol_bal                    466285 non-null  int64
 34  revol_util                   465945 non-null  float64
 35  total_acc                    466256 non-null  float64
 36  initial_list_status          466285 non-null  object
 37  out_prncp                    466285 non-null  float64
 38  out_prncp_inv                466285 non-null  float64
 39  total_pymnt                  466285 non-null  float64
 40  total_pymnt_inv              466285 non-null  float64
 41  total_rec_prncp              466285 non-null  float64
 42  total_rec_int                466285 non-null  float64
 43  total_rec_late_fee           466285 non-null  float64
 44  recoveries                   466285 non-null  float64
 45  collection_recovery_fee      466285 non-null  float64
 46  last_pymnt_d                 465909 non-null  object
 47  last_pymnt_amnt              466285 non-null  float64
 48  next_pymnt_d                 239071 non-null  object
 49  last_credit_pull_d           466243 non-null  object
 50  collections_12_mths_ex_med   466140 non-null  float64
 51  mths_since_last_major_derog  98974 non-null   float64
 52  policy_code                  466285 non-null  int64
 53  application_type             466285 non-null  object
 54  annual_inc_joint             0 non-null       float64
 55  dti_joint                    0 non-null       float64
 56  verification_status_joint    0 non-null       float64
 57  acc_now_delinq               466256 non-null  float64
 58  tot_coll_amt                 396009 non-null  float64
 59  tot_cur_bal                  396009 non-null  float64
 60  open_acc_6m                  0 non-null       float64
 61  open_il_6m                   0 non-null       float64
 62  open_il_12m                  0 non-null       float64
 63  open_il_24m                  0 non-null       float64
 64  mths_since_rcnt_il           0 non-null       float64
 65  total_bal_il                 0 non-null       float64
 66  il_util                      0 non-null       float64
 67  open_rv_12m                  0 non-null       float64
 68  open_rv_24m                  0 non-null       float64
 69  max_bal_bc                   0 non-null       float64
 70  all_util                     0 non-null       float64
 71  total_rev_hi_lim             396009 non-null  float64
 72  inq_fi                       0 non-null       float64
 73  total_cu_tl                  0 non-null       float64
 74  inq_last_12m                 0 non-null       float64
dtypes: float64(46), int64(7), object(22)
memory usage: 266.8+ MB

In [194]:
df.dropna(how='all', axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 58 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   466285 non-null  int64
 1   id                           466285 non-null  int64
 2   member_id                    466285 non-null  int64
 3   loan_amnt                    466285 non-null  int64
 4   funded_amnt                  466285 non-null  int64
 5   funded_amnt_inv              466285 non-null  float64
 6   term                         466285 non-null  object
 7   int_rate                     466285 non-null  float64
 8   installment                  466285 non-null  float64
 9   grade                        466285 non-null  object
 10  sub_grade                    466285 non-null  object
 11  emp_title                    438697 non-null  object
 12  emp_length                   445277 non-null  object
 13  home_ownership               466285 non-null  object
 14  annual_inc                   466281 non-null  float64
 15  verification_status          466285 non-null  object
 16  issue_d                      466285 non-null  object
 17  loan_status                  466285 non-null  object
 18  pymnt_plan                   466285 non-null  object
 19  url                          466285 non-null  object
 20  desc                         125981 non-null  object
 21  purpose                      466285 non-null  object
 22  title                        466264 non-null  object
 23  zip_code                     466285 non-null  object
 24  addr_state                   466285 non-null  object
 25  dti                          466285 non-null  float64
 26  delinq_2yrs                  466256 non-null  float64
 27  earliest_cr_line             466256 non-null  object
 28  inq_last_6mths               466256 non-null  float64
 29  mths_since_last_delinq       215934 non-null  float64
 30  mths_since_last_record       62638 non-null   float64
 31  open_acc                     466256 non-null  float64
 32  pub_rec                      466256 non-null  float64
 33  revol_bal                    466285 non-null  int64
 34  revol_util                   465945 non-null  float64
 35  total_acc                    466256 non-null  float64
 36  initial_list_status          466285 non-null  object
 37  out_prncp                    466285 non-null  float64
 38  out_prncp_inv                466285 non-null  float64
 39  total_pymnt                  466285 non-null  float64
 40  total_pymnt_inv              466285 non-null  float64
 41  total_rec_prncp              466285 non-null  float64
 42  total_rec_int                466285 non-null  float64
 43  total_rec_late_fee           466285 non-null  float64
 44  recoveries                   466285 non-null  float64
 45  collection_recovery_fee      466285 non-null  float64
 46  last_pymnt_d                 465909 non-null  object
 47  last_pymnt_amnt              466285 non-null  float64
 48  next_pymnt_d                 239071 non-null  object
 49  last_credit_pull_d           466243 non-null  object
 50  collections_12_mths_ex_med   466140 non-null  float64
 51  mths_since_last_major_derog  98974 non-null   float64
 52  policy_code                  466285 non-null  int64
 53  application_type             466285 non-null  object
 54  acc_now_delinq               466256 non-null  float64
 55  tot_coll_amt                 396009 non-null  float64
 56  tot_cur_bal                  396009 non-null  float64
 57  total_rev_hi_lim             396009 non-null  float64
dtypes: float64(29), int64(7), object(22)
memory usage: 206.3+ MB

In [195]:
df.drop(columns=['Unnamed: 0','id','member_id'], inplace=True)
df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,...,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim
0,5000,5000,4975.0,36 months,10.65,162.87,B,B2,None,10+ years,...,None,Jan-16,0.0,NaN,1,INDIVIDUAL,0.0,NaN,NaN,NaN
1,2500,2500,2500.0,60 months,15.27,59.83,C,C4,Ryder,< 1 year,...,None,Sep-13,0.0,NaN,1,INDIVIDUAL,0.0,NaN,NaN,NaN
2,2400,2400,2400.0,36 months,15.96,84.33,C,C5,None,10+ years,...,None,Jan-16,0.0,NaN,1,INDIVIDUAL,0.0,NaN,NaN,NaN
3,10000,10000,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,...,None,Jan-15,0.0,NaN,1,INDIVIDUAL,0.0,NaN,NaN,NaN
4,3000,3000,3000.0,60 months,12.69,67.79,B,B5,University Medical Group,1 year,...,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,0.0,NaN,NaN,NaN

In [196]:
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 55 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   loan_amnt                    466285 non-null  int64
 1   funded_amnt                  466285 non-null  int64
 2   funded_amnt_inv              466285 non-null  float64
 3   term                         466285 non-null  object
 4   int_rate                     466285 non-null  float64
 5   installment                  466285 non-null  float64
 6   grade                        466285 non-null  object
 7   sub_grade                    466285 non-null  object
 8   emp_title                    438697 non-null  object
 9   emp_length                   445277 non-null  object
 10  home_ownership               466285 non-null  object
 11  annual_inc                   466281 non-null  float64
 12  verification_status          466285 non-null  object
 13  issue_d                      466285 non-null  object
 14  loan_status                  466285 non-null  object
 15  pymnt_plan                   466285 non-null  object
 16  url                          466285 non-null  object
 17  desc                         125981 non-null  object
 18  purpose                      466285 non-null  object
 19  title                        466264 non-null  object
 20  zip_code                     466285 non-null  object
 21  addr_state                   466285 non-null  object
 22  dti                          466285 non-null  float64
 23  delinq_2yrs                  466256 non-null  float64
 24  earliest_cr_line             466256 non-null  object
 25  inq_last_6mths               466256 non-null  float64
 26  mths_since_last_delinq       215934 non-null  float64
 27  mths_since_last_record       62638 non-null   float64
 28  open_acc                     466256 non-null  float64
 29  pub_rec                      466256 non-null  float64
 30  revol_bal                    466285 non-null  int64
 31  revol_util                   465945 non-null  float64
 32  total_acc                    466256 non-null  float64
 33  initial_list_status          466285 non-null  object
 34  out_prncp                    466285 non-null  float64
 35  out_prncp_inv                466285 non-null  float64
 36  total_pymnt                  466285 non-null  float64
 37  total_pymnt_inv              466285 non-null  float64
 38  total_rec_prncp              466285 non-null  float64
 39  total_rec_int                466285 non-null  float64
 40  total_rec_late_fee           466285 non-null  float64
 41  recoveries                   466285 non-null  float64
 42  collection_recovery_fee      466285 non-null  float64
 43  last_pymnt_d                 465909 non-null  object
 44  last_pymnt_amnt              466285 non-null  float64
 45  next_pymnt_d                 239071 non-null  object
 46  last_credit_pull_d           466243 non-null  object
 47  collections_12_mths_ex_med   466140 non-null  float64
 48  mths_since_last_major_derog  98974 non-null   float64
 49  policy_code                  466285 non-null  int64
 50  application_type             466285 non-null  object
 51  acc_now_delinq               466256 non-null  float64
 52  tot_coll_amt                 396009 non-null  float64
 53  tot_cur_bal                  396009 non-null  float64
 54  total_rev_hi_lim             396009 non-null  float64
dtypes: float64(29), int64(4), object(22)
memory usage: 195.7+ MB

In [197]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 55 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   loan_amnt                    466285 non-null  int64
 1   funded_amnt                  466285 non-null  int64
 2   funded_amnt_inv              466285 non-null  float64
 3   term                         466285 non-null  object
 4   int_rate                     466285 non-null  float64
 5   installment                  466285 non-null  float64
 6   grade                        466285 non-null  object
 7   sub_grade                    466285 non-null  object
 8   emp_title                    438697 non-null  object
 9   emp_length                   445277 non-null  object
 10  home_ownership               466285 non-null  object
 11  annual_inc                   466281 non-null  float64
 12  verification_status          466285 non-null  object
 13  issue_d                      466285 non-null  object
 14  loan_status                  466285 non-null  object
 15  pymnt_plan                   466285 non-null  object
 16  url                          466285 non-null  object
 17  desc                         125981 non-null  object
 18  purpose                      466285 non-null  object
 19  title                        466264 non-null  object
 20  zip_code                     466285 non-null  object
 21  addr_state                   466285 non-null  object
 22  dti                          466285 non-null  float64
 23  delinq_2yrs                  466256 non-null  float64
 24  earliest_cr_line             466256 non-null  object
 25  inq_last_6mths               466256 non-null  float64
 26  mths_since_last_delinq       215934 non-null  float64
 27  mths_since_last_record       62638 non-null   float64
 28  open_acc                     466256 non-null  float64
 29  pub_rec                      466256 non-null  float64
 30  revol_bal                    466285 non-null  int64
 31  revol_util                   465945 non-null  float64
 32  total_acc                    466256 non-null  float64
 33  initial_list_status          466285 non-null  object
 34  out_prncp                    466285 non-null  float64
 35  out_prncp_inv                466285 non-null  float64
 36  total_pymnt                  466285 non-null  float64
 37  total_pymnt_inv              466285 non-null  float64
 38  total_rec_prncp              466285 non-null  float64
 39  total_rec_int                466285 non-null  float64
 40  total_rec_late_fee           466285 non-null  float64
 41  recoveries                   466285 non-null  float64
 42  collection_recovery_fee      466285 non-null  float64
 43  last_pymnt_d                 465909 non-null  object
 44  last_pymnt_amnt              466285 non-null  float64
 45  next_pymnt_d                 239071 non-null  object
 46  last_credit_pull_d           466243 non-null  object
 47  collections_12_mths_ex_med   466140 non-null  float64
 48  mths_since_last_major_derog  98974 non-null   float64
 49  policy_code                  466285 non-null  int64
 50  application_type             466285 non-null  object
 51  acc_now_delinq               466256 non-null  float64
 52  tot_coll_amt                 396009 non-null  float64
 53  tot_cur_bal                  396009 non-null  float64
 54  total_rev_hi_lim             396009 non-null  float64
dtypes: float64(29), int64(4), object(22)
memory usage: 195.7+ MB

In [198]:
str_list=[]

for x in df:
    if df[x].dtype == 'object':
        str_list.append(x)
print(str_list)

['term', 'grade', 'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 'verification_status', 'issue_d', 'loan_status', 'pymnt_plan', 'url', 'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'earliest_cr_line', 'initial_list_status', 'last_pymnt_d', 'next_pymnt_d', 'last_credit_pull_d', 'application_type']

In [199]:
df[str_list].transpose().head(22)

,0,1,2,3,4,5,6,7,8,9,...,466275,466276,466277,466278,466279,466280,466281,466282,466283,466284
term,36 months,60 months,36 months,36 months,60 months,36 months,60 months,36 months,60 months,60 months,...,36 months,60 months,36 months,36 months,36 months,60 months,60 months,60 months,36 months,36 months
grade,B,C,C,C,B,A,C,E,F,B,...,C,D,A,D,B,C,D,D,A,D
sub_grade,B2,C4,C5,C1,B5,A4,C5,E1,F2,B5,...,C4,D3,A4,D3,B5,C2,D5,D1,A4,D3
emp_title,None,Ryder,None,AIR RESOURCES BOARD,University Medical Group,Veolia Transportaton,Southern Star Photography,MKC Accounting,None,Starbucks,...,manager,MANAGER,sales rep,MecÃ¡nica,Director of Operations,Financial Advisor,Chief of Interpretation (Park Ranger),patrol,Server Engineer Lead,None
emp_length,10+ years,< 1 year,10+ years,10+ years,1 year,3 years,8 years,9 years,4 years,< 1 year,...,7 years,5 years,3 years,10+ years,4 years,4 years,10+ years,7 years,3 years,10+ years
home_ownership,RENT,RENT,RENT,RENT,RENT,RENT,RENT,RENT,OWN,RENT,...,RENT,MORTGAGE,RENT,RENT,RENT,MORTGAGE,MORTGAGE,MORTGAGE,OWN,MORTGAGE
verification_status,Verified,Source Verified,Not Verified,Source Verified,Source Verified,Source Verified,Not Verified,Source Verified,Source Verified,Verified,...,Verified,Verified,Verified,Source Verified,Source Verified,Source Verified,Verified,Verified,Verified,Verified
issue_d,Dec-11,Dec-11,Dec-11,Dec-11,Dec-11,Dec-11,Dec-11,Dec-11,Dec-11,Dec-11,...,Jan-14,Jan-14,Jan-14,Jan-14,Jan-14,Jan-14,Jan-14,Jan-14,Jan-14,Jan-14
loan_status,Fully Paid,Charged Off,Fully Paid,Fully Paid,Current,Fully Paid,Current,Fully Paid,Charged Off,Charged Off,...,Fully Paid,Charged Off,Charged Off,Fully Paid,Current,Current,Charged Off,Current,Fully Paid,Current
pymnt_plan,n,n,n,n,n,n,n,n,n,n,...,n,n,n,n,n,n,n,n,n,n
url,https://www.lendingclub.com/browse/loanDetail....,https://www.lendingclub.com/browse/loanDetail....,https://www.lendingclub.com/browse/loanDetail....,https://www.lendingclub.com/browse/loanDetail....,https://www.lendingclub.com/browse/loanDetail....,https://www.lendingclub.com/browse/loanDetail....,https://www.lendingclub.com/browse/loanDetail....,https://www.lendingclub.com/browse/loanDetail....,https://www.lendingclub.com/browse/loanDetail....,https://www.lendingclub.com/browse/loanDetail....,...,https://www.lendingclub.com/browse/loanDetail....,https://www.lendingclub.com/browse/loanDetail....,https://www.lendingclub.com/browse/loanDetail....,https://www.lendingclub.com/browse/loanDetail....,https://www.lendingclub.com/browse/loanDetail....,https://www.lendingclub.com/browse/loanDetail....,https://www.lendingclub.com/browse/loanDetail....,https://www.lendingclub.com/browse/loanDetail....,https://www.lendingclub.com/browse/loanDetail....,https://www.lendingclub.com/browse/loanDetail....
desc,Borrower added on 12/22/11 > I need to upgra...,Borrower added on 12/22/11 > I plan to use t...,None,Borrower added on 12/21/11 > to pay for prop...,Borrower added on 12/21/11 > I plan on combi...,None,Borrower added on 12/18/11 > I am planning o...,Borrower added on 12/16/11 > Downpayment for...,Borrower added on 12/21/11 > I own a small h...,Borrower added on 12/16/11 > I'm trying to b...,...,None,None,Borrower added on 12/09/13 > consolidate all...,None,None,None,None,Borrower added on 12/06/13 > I am going to c...,None,Borrower added on 12/04/13 > I will like a l...
purpose,credit_card,car,small_business,other,other,wedding,debt_consolidation,car,small_business,other,...,credit_card,medical,debt_consolidation,vacation,credit_card,debt_consolidation,debt_consolidation,debt_consolidation,credit_card,other
title,Computer,bike,real estate business,personel,Personal,My wedding loan I promise to pay back,Loan,Car Downpayment,Expand Business & Buy Debt Portfolio,Building my credit history.,...,Credit card refinancing,Medical expenses,my loan,Vacation,Credit card refinancing,Debt consolidation,Debt consolidation,Debt consolidation,Credit card refinancing,Other
zip_code,860xx,309xx,606xx,917xx,972xx,852xx,280xx,900xx,958xx,774xx,...,913xx,011xx,212xx,201xx,208xx,773xx,377xx,458xx,913xx,950xx
addr_state,AZ,GA,IL,CA,OR,AZ,NC,CA,CA,TX,...,CA,MA,MD,VA,MD,TX,TN,OH,CA,CA
earliest_cr_line,Jan-85,Apr-99,Nov-01,Feb-96,Jan-96,Nov-04,Jul-05,Jan-07,Apr-04,Sep-04,...,Nov-93,Nov-94,Jul-98,Jun-02,Aug-99,Apr-03,Jun-97,Dec-01,Feb-03,Feb-00
initial_list_status,f,f,f,f,f,f,f,f,f,f,...,f,f,f,f,w,w,f,f,w,f
last_pymnt_d,Jan-15,Apr-13,Jun-14,Jan-15,Jan-16,Jan-15,Jan-16,Jan-15,Apr-12,Nov-12,...,Mar-15,May-14,Nov-14,Sep-15,Jan-16,Jan-16,Dec-14,Jan-16,Dec-14,Jan-16
next_pymnt_d,None,None,None,None,Feb-16,None,Feb-16,None,None,None,...,None,None,None,None,Feb-16,Feb-16,None,Feb-16,None,Feb-16
last_credit_pull_d,Jan-16,Sep-13,Jan-16,Jan-15,Jan-16,Sep-15,Jan-16,Dec-14,Aug-12,Mar-13,...,Jan-16,Oct-14,Oct-14,Jan-16,Jan-16,Jan-16,Jan-16,Dec-15,Apr-15,Jan-16
application_type,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL,...,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL,INDIVIDUAL

In [200]:
df[str_list].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 22 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   term                 466285 non-null  object
 1   grade                466285 non-null  object
 2   sub_grade            466285 non-null  object
 3   emp_title            438697 non-null  object
 4   emp_length           445277 non-null  object
 5   home_ownership       466285 non-null  object
 6   verification_status  466285 non-null  object
 7   issue_d              466285 non-null  object
 8   loan_status          466285 non-null  object
 9   pymnt_plan           466285 non-null  object
 10  url                  466285 non-null  object
 11  desc                 125981 non-null  object
 12  purpose              466285 non-null  object
 13  title                466264 non-null  object
 14  zip_code             466285 non-null  object
 15  addr_state           466285 non-null  object
 16  earliest_cr_line     466256 non-null  object
 17  initial_list_status  466285 non-null  object
 18  last_pymnt_d         465909 non-null  object
 19  next_pymnt_d         239071 non-null  object
 20  last_credit_pull_d   466243 non-null  object
 21  application_type     466285 non-null  object
dtypes: object(22)
memory usage: 78.3+ MB

In [201]:
for col in str_list:
    if col=='issue_d' or col=='earliest_cr_line' or col=='last_pymnt_d' or col=='next_pymnt_d' or col=='last_credit_pull_d':
        str_list.remove(col)

print(str_list)

['term', 'grade', 'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 'verification_status', 'loan_status', 'pymnt_plan', 'url', 'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'initial_list_status', 'next_pymnt_d', 'application_type']

In [202]:
str_list.remove('next_pymnt_d')
str_list.remove('term')
str_list.remove('emp_length')

In [203]:
date_list=['issue_d','earliest_cr_line','last_pymnt_d','next_pymnt_d','last_credit_pull_d']
df[date_list].head()

  issue_d earliest_cr_line last_pymnt_d next_pymnt_d last_credit_pull_d
0  Dec-11           Jan-85       Jan-15         None             Jan-16
1  Dec-11           Apr-99       Apr-13         None             Sep-13
2  Dec-11           Nov-01       Jun-14         None             Jan-16
3  Dec-11           Feb-96       Jan-15         None             Jan-15
4  Dec-11           Jan-96       Jan-16       Feb-16             Jan-16

In [204]:
for c in date_list:
	df[c] = pd.to_datetime(df[c], format='%b-%y', errors='coerce')
df[date_list].head()

     issue_d earliest_cr_line last_pymnt_d next_pymnt_d last_credit_pull_d
0 2011-12-01       1985-01-01   2015-01-01          NaT         2016-01-01
1 2011-12-01       1999-04-01   2013-04-01          NaT         2013-09-01
2 2011-12-01       2001-11-01   2014-06-01          NaT         2016-01-01
3 2011-12-01       1996-02-01   2015-01-01          NaT         2015-01-01
4 2011-12-01       1996-01-01   2016-01-01   2016-02-01         2016-01-01

In [205]:
df['term'] = (df['term'].str.replace(' months', '').astype(int))
df['emp_length'] = df['emp_length'].fillna('0').str.replace(' years', '').str.replace(' year', '').str.replace('< 1', '0').str.replace('10+', '10').astype(int)
df[['term','emp_length']].head()

   term  emp_length
0    36          10
1    60           0
2    36          10
3    36          10
4    60           1

In [206]:
df[str_list].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 15 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   grade                466285 non-null  object
 1   sub_grade            466285 non-null  object
 2   emp_title            438697 non-null  object
 3   home_ownership       466285 non-null  object
 4   verification_status  466285 non-null  object
 5   loan_status          466285 non-null  object
 6   pymnt_plan           466285 non-null  object
 7   url                  466285 non-null  object
 8   desc                 125981 non-null  object
 9   purpose              466285 non-null  object
 10  title                466264 non-null  object
 11  zip_code             466285 non-null  object
 12  addr_state           466285 non-null  object
 13  initial_list_status  466285 non-null  object
 14  application_type     466285 non-null  object
dtypes: object(15)
memory usage: 53.4+ MB

In [207]:
df['emp_length'].value_counts()

emp_length
10    150049
0      57273
2      41373
3      36596
5      30774
1      29622
4      28023
7      26180
6      26112
8      22395
9      17888
Name: count, dtype: int64

### Important: Variable of Interest (Dependent Variable):

In [208]:
df['loan_status'].value_counts()

loan_status
Current                                                224226
Fully Paid                                             184739
Charged Off                                             42475
Late (31-120 days)                                       6900
In Grace Period                                          3146
Does not meet the credit policy. Status:Fully Paid       1988
Late (16-30 days)                                        1218
Default                                                   832
Does not meet the credit policy. Status:Charged Off       761
Name: count, dtype: int64

In [209]:
for col in df[str_list]:
    cardinality = len(pd.Index(df[col]).value_counts())
    print(df[col].name + ": " + str(cardinality))

grade: 7
sub_grade: 35
emp_title: 205475
home_ownership: 6
verification_status: 3
loan_status: 9
pymnt_plan: 2
url: 466285
desc: 124435
purpose: 14
title: 63098
zip_code: 888
addr_state: 50
initial_list_status: 2
application_type: 1

In [210]:
df['emp_title']=df['emp_title'].str.lower()
df['emp_title']

0                                          None
1                                         ryder
2                                          None
3                           air resources board
4                      university medical group
                          ...
466280                       financial advisor
466281    chief of interpretation (park ranger)
466282                                   patrol
466283                     server engineer lead
466284                                     None
Name: emp_title, Length: 466285, dtype: object

In [211]:
# df['emp_title']=title_emp
for coly in df[str_list]:
    cardinality = len(pd.Index(df[coly]).value_counts())
    print(df[coly].name + ": " + str(cardinality))

grade: 7
sub_grade: 35
emp_title: 183322
home_ownership: 6
verification_status: 3
loan_status: 9
pymnt_plan: 2
url: 466285
desc: 124435
purpose: 14
title: 63098
zip_code: 888
addr_state: 50
initial_list_status: 2
application_type: 1

In [212]:
print(df['emp_title'].value_counts())

emp_title
teacher                         6663
manager                         6005
registered nurse                3278
supervisor                      2857
owner                           2485
                                ...
shma                               1
cookeville housing authority       1
production manufacturing           1
adm-stratas foods                  1
server engineer lead               1
Name: count, Length: 183322, dtype: int64

In [213]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 55 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   loan_amnt                    466285 non-null  int64
 1   funded_amnt                  466285 non-null  int64
 2   funded_amnt_inv              466285 non-null  float64
 3   term                         466285 non-null  int64
 4   int_rate                     466285 non-null  float64
 5   installment                  466285 non-null  float64
 6   grade                        466285 non-null  object
 7   sub_grade                    466285 non-null  object
 8   emp_title                    438697 non-null  object
 9   emp_length                   466285 non-null  int64
 10  home_ownership               466285 non-null  object
 11  annual_inc                   466281 non-null  float64
 12  verification_status          466285 non-null  object
 13  issue_d                      466285 non-null  datetime64[ns]
 14  loan_status                  466285 non-null  object
 15  pymnt_plan                   466285 non-null  object
 16  url                          466285 non-null  object
 17  desc                         125981 non-null  object
 18  purpose                      466285 non-null  object
 19  title                        466264 non-null  object
 20  zip_code                     466285 non-null  object
 21  addr_state                   466285 non-null  object
 22  dti                          466285 non-null  float64
 23  delinq_2yrs                  466256 non-null  float64
 24  earliest_cr_line             466256 non-null  datetime64[ns]
 25  inq_last_6mths               466256 non-null  float64
 26  mths_since_last_delinq       215934 non-null  float64
 27  mths_since_last_record       62638 non-null   float64
 28  open_acc                     466256 non-null  float64
 29  pub_rec                      466256 non-null  float64
 30  revol_bal                    466285 non-null  int64
 31  revol_util                   465945 non-null  float64
 32  total_acc                    466256 non-null  float64
 33  initial_list_status          466285 non-null  object
 34  out_prncp                    466285 non-null  float64
 35  out_prncp_inv                466285 non-null  float64
 36  total_pymnt                  466285 non-null  float64
 37  total_pymnt_inv              466285 non-null  float64
 38  total_rec_prncp              466285 non-null  float64
 39  total_rec_int                466285 non-null  float64
 40  total_rec_late_fee           466285 non-null  float64
 41  recoveries                   466285 non-null  float64
 42  collection_recovery_fee      466285 non-null  float64
 43  last_pymnt_d                 465909 non-null  datetime64[ns]
 44  last_pymnt_amnt              466285 non-null  float64
 45  next_pymnt_d                 239071 non-null  datetime64[ns]
 46  last_credit_pull_d           466243 non-null  datetime64[ns]
 47  collections_12_mths_ex_med   466140 non-null  float64
 48  mths_since_last_major_derog  98974 non-null   float64
 49  policy_code                  466285 non-null  int64
 50  application_type             466285 non-null  object
 51  acc_now_delinq               466256 non-null  float64
 52  tot_coll_amt                 396009 non-null  float64
 53  tot_cur_bal                  396009 non-null  float64
 54  total_rev_hi_lim             396009 non-null  float64
dtypes: datetime64[ns](5), float64(29), int64(6), object(15)
memory usage: 195.7+ MB

In [214]:
if 'unemployed' in df['emp_title'].values:
    print('founded')
else:
    print('No unemployed')

No unemployed

In [215]:
df['emp_title'].fillna('unemployed', inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 55 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   loan_amnt                    466285 non-null  int64
 1   funded_amnt                  466285 non-null  int64
 2   funded_amnt_inv              466285 non-null  float64
 3   term                         466285 non-null  int64
 4   int_rate                     466285 non-null  float64
 5   installment                  466285 non-null  float64
 6   grade                        466285 non-null  object
 7   sub_grade                    466285 non-null  object
 8   emp_title                    466285 non-null  object
 9   emp_length                   466285 non-null  int64
 10  home_ownership               466285 non-null  object
 11  annual_inc                   466281 non-null  float64
 12  verification_status          466285 non-null  object
 13  issue_d                      466285 non-null  datetime64[ns]
 14  loan_status                  466285 non-null  object
 15  pymnt_plan                   466285 non-null  object
 16  url                          466285 non-null  object
 17  desc                         125981 non-null  object
 18  purpose                      466285 non-null  object
 19  title                        466264 non-null  object
 20  zip_code                     466285 non-null  object
 21  addr_state                   466285 non-null  object
 22  dti                          466285 non-null  float64
 23  delinq_2yrs                  466256 non-null  float64
 24  earliest_cr_line             466256 non-null  datetime64[ns]
 25  inq_last_6mths               466256 non-null  float64
 26  mths_since_last_delinq       215934 non-null  float64
 27  mths_since_last_record       62638 non-null   float64
 28  open_acc                     466256 non-null  float64
 29  pub_rec                      466256 non-null  float64
 30  revol_bal                    466285 non-null  int64
 31  revol_util                   465945 non-null  float64
 32  total_acc                    466256 non-null  float64
 33  initial_list_status          466285 non-null  object
 34  out_prncp                    466285 non-null  float64
 35  out_prncp_inv                466285 non-null  float64
 36  total_pymnt                  466285 non-null  float64
 37  total_pymnt_inv              466285 non-null  float64
 38  total_rec_prncp              466285 non-null  float64
 39  total_rec_int                466285 non-null  float64
 40  total_rec_late_fee           466285 non-null  float64
 41  recoveries                   466285 non-null  float64
 42  collection_recovery_fee      466285 non-null  float64
 43  last_pymnt_d                 465909 non-null  datetime64[ns]
 44  last_pymnt_amnt              466285 non-null  float64
 45  next_pymnt_d                 239071 non-null  datetime64[ns]
 46  last_credit_pull_d           466243 non-null  datetime64[ns]
 47  collections_12_mths_ex_med   466140 non-null  float64
 48  mths_since_last_major_derog  98974 non-null   float64
 49  policy_code                  466285 non-null  int64
 50  application_type             466285 non-null  object
 51  acc_now_delinq               466256 non-null  float64
 52  tot_coll_amt                 396009 non-null  float64
 53  tot_cur_bal                  396009 non-null  float64
 54  total_rev_hi_lim             396009 non-null  float64
dtypes: datetime64[ns](5), float64(29), int64(6), object(15)
memory usage: 195.7+ MB

In [216]:
df['emp_title'].value_counts()

emp_title
unemployed                               27588
teacher                                   6663
manager                                   6005
registered nurse                          3278
supervisor                                2857
                                         ...
linde electronics and specialty gases        1
shma                                         1
cookeville housing authority                 1
production manufacturing                     1
server engineer lead                         1
Name: count, Length: 183323, dtype: int64

In [217]:
num_list=[]
for x in df:
    if df[x].dtype == 'int64' or df[x].dtype == 'float64':
        num_list.append(x)
df[num_list].head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,emp_length,annual_inc,dti,delinq_2yrs,...,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim
0,5000,5000,4975.0,36,10.65,162.87,10,24000.0,27.65,0.0,...,0.00,0.00,171.62,0.0,NaN,1,0.0,NaN,NaN,NaN
1,2500,2500,2500.0,60,15.27,59.83,0,30000.0,1.00,0.0,...,117.08,1.11,119.66,0.0,NaN,1,0.0,NaN,NaN,NaN
2,2400,2400,2400.0,36,15.96,84.33,10,12252.0,8.72,0.0,...,0.00,0.00,649.91,0.0,NaN,1,0.0,NaN,NaN,NaN
3,10000,10000,10000.0,36,13.49,339.31,10,49200.0,20.00,0.0,...,0.00,0.00,357.48,0.0,NaN,1,0.0,NaN,NaN,NaN
4,3000,3000,3000.0,60,12.69,67.79,1,80000.0,17.94,0.0,...,0.00,0.00,67.79,0.0,NaN,1,0.0,NaN,NaN,NaN

In [218]:
df[num_list].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 35 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   loan_amnt                    466285 non-null  int64
 1   funded_amnt                  466285 non-null  int64
 2   funded_amnt_inv              466285 non-null  float64
 3   term                         466285 non-null  int64
 4   int_rate                     466285 non-null  float64
 5   installment                  466285 non-null  float64
 6   emp_length                   466285 non-null  int64
 7   annual_inc                   466281 non-null  float64
 8   dti                          466285 non-null  float64
 9   delinq_2yrs                  466256 non-null  float64
 10  inq_last_6mths               466256 non-null  float64
 11  mths_since_last_delinq       215934 non-null  float64
 12  mths_since_last_record       62638 non-null   float64
 13  open_acc                     466256 non-null  float64
 14  pub_rec                      466256 non-null  float64
 15  revol_bal                    466285 non-null  int64
 16  revol_util                   465945 non-null  float64
 17  total_acc                    466256 non-null  float64
 18  out_prncp                    466285 non-null  float64
 19  out_prncp_inv                466285 non-null  float64
 20  total_pymnt                  466285 non-null  float64
 21  total_pymnt_inv              466285 non-null  float64
 22  total_rec_prncp              466285 non-null  float64
 23  total_rec_int                466285 non-null  float64
 24  total_rec_late_fee           466285 non-null  float64
 25  recoveries                   466285 non-null  float64
 26  collection_recovery_fee      466285 non-null  float64
 27  last_pymnt_amnt              466285 non-null  float64
 28  collections_12_mths_ex_med   466140 non-null  float64
 29  mths_since_last_major_derog  98974 non-null   float64
 30  policy_code                  466285 non-null  int64
 31  acc_now_delinq               466256 non-null  float64
 32  tot_coll_amt                 396009 non-null  float64
 33  tot_cur_bal                  396009 non-null  float64
 34  total_rev_hi_lim             396009 non-null  float64
dtypes: float64(29), int64(6)
memory usage: 124.5 MB

In [219]:
for col in df[num_list].columns:
    if any(df[col].isnull())==True:
        print(col, df[col].isnull().sum())

annual_inc 4
delinq_2yrs 29
inq_last_6mths 29
mths_since_last_delinq 250351
mths_since_last_record 403647
open_acc 29
pub_rec 29
revol_util 340
total_acc 29
collections_12_mths_ex_med 145
mths_since_last_major_derog 367311
acc_now_delinq 29
tot_coll_amt 70276
tot_cur_bal 70276
total_rev_hi_lim 70276

### How to treat null values
- annual_inc: remove rows with null values
- delinq_2yrs: set to 0
- inq_last_6mths: set to 0
- mths_since_last_delinq: set to 0
- mths_since_last_record: set to 0
- open_acc: set to 1
- pub_rec: set to 0
- revol_util: set to 0
- total_acc: set to 1
- collections_12_mths_ex_med: set to 0
- mths_since_last_major_derog: set to 0
- acc_now_delinq: set to 0
- tot_coll_amt: set to 0
- tot_cur_bal: set to 0
- total_rev_hi_lim: set to 0

In [220]:
df=df[df['annual_inc'].notna()]
df['open_acc'].fillna(1, inplace=True)
df['total_acc'].fillna(1, inplace=True)

C:\Users\daru1\AppData\Local\Temp\ipykernel_10908\1977375094.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['open_acc'].fillna(1, inplace=True)
C:\Users\daru1\AppData\Local\Temp\ipykernel_10908\1977375094.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['total_acc'].fillna(1, inplace=True)

In [221]:
for col in ['delinq_2yrs', 'inq_last_6mths','mths_since_last_delinq','mths_since_last_record','pub_rec','revol_util','collections_12_mths_ex_med','mths_since_last_major_derog','acc_now_delinq','tot_coll_amt','tot_cur_bal','total_rev_hi_lim']:
    df[col].fillna(0, inplace=True)

C:\Users\daru1\AppData\Local\Temp\ipykernel_10908\3771396555.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(0, inplace=True)

In [222]:
df[num_list].info()

<class 'pandas.core.frame.DataFrame'>
Index: 466281 entries, 0 to 466284
Data columns (total 35 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   loan_amnt                    466281 non-null  int64
 1   funded_amnt                  466281 non-null  int64
 2   funded_amnt_inv              466281 non-null  float64
 3   term                         466281 non-null  int64
 4   int_rate                     466281 non-null  float64
 5   installment                  466281 non-null  float64
 6   emp_length                   466281 non-null  int64
 7   annual_inc                   466281 non-null  float64
 8   dti                          466281 non-null  float64
 9   delinq_2yrs                  466281 non-null  float64
 10  inq_last_6mths               466281 non-null  float64
 11  mths_since_last_delinq       466281 non-null  float64
 12  mths_since_last_record       466281 non-null  float64
 13  open_acc                     466281 non-null  float64
 14  pub_rec                      466281 non-null  float64
 15  revol_bal                    466281 non-null  int64
 16  revol_util                   466281 non-null  float64
 17  total_acc                    466281 non-null  float64
 18  out_prncp                    466281 non-null  float64
 19  out_prncp_inv                466281 non-null  float64
 20  total_pymnt                  466281 non-null  float64
 21  total_pymnt_inv              466281 non-null  float64
 22  total_rec_prncp              466281 non-null  float64
 23  total_rec_int                466281 non-null  float64
 24  total_rec_late_fee           466281 non-null  float64
 25  recoveries                   466281 non-null  float64
 26  collection_recovery_fee      466281 non-null  float64
 27  last_pymnt_amnt              466281 non-null  float64
 28  collections_12_mths_ex_med   466281 non-null  float64
 29  mths_since_last_major_derog  466281 non-null  float64
 30  policy_code                  466281 non-null  int64
 31  acc_now_delinq               466281 non-null  float64
 32  tot_coll_amt                 466281 non-null  float64
 33  tot_cur_bal                  466281 non-null  float64
 34  total_rev_hi_lim             466281 non-null  float64
dtypes: float64(29), int64(6)
memory usage: 128.1 MB

In [223]:
for col in df.columns:
    if any(df[col].isnull())==True:
        df.drop(columns=col, inplace=True)

In [224]:
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 466281 entries, 0 to 466284
Data columns (total 49 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   loan_amnt                    466281 non-null  int64
 1   funded_amnt                  466281 non-null  int64
 2   funded_amnt_inv              466281 non-null  float64
 3   term                         466281 non-null  int64
 4   int_rate                     466281 non-null  float64
 5   installment                  466281 non-null  float64
 6   grade                        466281 non-null  object
 7   sub_grade                    466281 non-null  object
 8   emp_title                    466281 non-null  object
 9   emp_length                   466281 non-null  int64
 10  home_ownership               466281 non-null  object
 11  annual_inc                   466281 non-null  float64
 12  verification_status          466281 non-null  object
 13  issue_d                      466281 non-null  datetime64[ns]
 14  loan_status                  466281 non-null  object
 15  pymnt_plan                   466281 non-null  object
 16  url                          466281 non-null  object
 17  purpose                      466281 non-null  object
 18  zip_code                     466281 non-null  object
 19  addr_state                   466281 non-null  object
 20  dti                          466281 non-null  float64
 21  delinq_2yrs                  466281 non-null  float64
 22  inq_last_6mths               466281 non-null  float64
 23  mths_since_last_delinq       466281 non-null  float64
 24  mths_since_last_record       466281 non-null  float64
 25  open_acc                     466281 non-null  float64
 26  pub_rec                      466281 non-null  float64
 27  revol_bal                    466281 non-null  int64
 28  revol_util                   466281 non-null  float64
 29  total_acc                    466281 non-null  float64
 30  initial_list_status          466281 non-null  object
 31  out_prncp                    466281 non-null  float64
 32  out_prncp_inv                466281 non-null  float64
 33  total_pymnt                  466281 non-null  float64
 34  total_pymnt_inv              466281 non-null  float64
 35  total_rec_prncp              466281 non-null  float64
 36  total_rec_int                466281 non-null  float64
 37  total_rec_late_fee           466281 non-null  float64
 38  recoveries                   466281 non-null  float64
 39  collection_recovery_fee      466281 non-null  float64
 40  last_pymnt_amnt              466281 non-null  float64
 41  collections_12_mths_ex_med   466281 non-null  float64
 42  mths_since_last_major_derog  466281 non-null  float64
 43  policy_code                  466281 non-null  int64
 44  application_type             466281 non-null  object
 45  acc_now_delinq               466281 non-null  float64
 46  tot_coll_amt                 466281 non-null  float64
 47  tot_cur_bal                  466281 non-null  float64
 48  total_rev_hi_lim             466281 non-null  float64
dtypes: datetime64[ns](1), float64(29), int64(6), object(13)
memory usage: 177.9+ MB